name: 522groupenv.yaml
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - jupyter
  - ucimlrepo
  - scikit-learn
  - conda-lock
prefix: /home/tiantong/miniforge3/envs/522groupenv.yaml
